option to gather messages even without defaultMessage attribute
yahoo/babel-plugin-react-intl pull request #136
Opened 2018-03-23 15:28 UTC by bziorkiewicz

Should fix #43

2018-04-24 11:46 UTC, krzkaczor commented
This is very useful PR. Documentation doesnt mention the fact that you need to provide defaultMessage (which I think is not a great idea since I want to store all my translactions in json files).

2018-04-24 17:17 UTC, redonkulus commented
@bziorkiewicz want to add a test for the new option?

2018-04-24 17:30 UTC, SleepWalker commented
Btw, I have a similar #140 PR with tests included. But there are some bonus options :D and no docs.

P.s. this PR will break the logic, that clean ups the code from descriptions.

2018-04-24 17:57 UTC, langpavel commented
See also https://github.com/yahoo/babel-plugin-react-intl/pull/137#issuecomment-384022388

2018-04-24 18:00 UTC, redonkulus commented
@SleepWalker @langpavel I'm not familiar with the code, so I'm offering to help since there seems to be 3 PR's that do the same thing?

I just want to make sure we do not break any existing functionality, we have proper documentation and tests. I would prefer to consolidate the various PRs perhaps in favor of #140.

2018-04-24 18:10 UTC, langpavel commented
@redonkulus Yeah, there is too much forks and much more features around the github, seems like `babel-plugin-react-intl` is **really *carefully* maintained** (but this looks like not developed…)
Of course, I have all tests passed too and even more, I write new tests for new features in #137.

BTW @bziorkiewicz, please, what you think about #137, can it solve your problem, can you review it? I think I did better job :grin:

2018-09-19 10:02 UTC, rasendubi commented on src/index.js
> +                    if (descriptor.defaultMessage || opts.optionalDefaultMessages) {
This breaks the plugin when spreads are used. e.g., `defineMessages` test case fails:
```
import React, {Component} from 'react';
import {defineMessages, FormattedMessage} from 'react-intl';

const msgs = defineMessages({
    header: {
        id: 'foo.bar.baz',
        defaultMessage: 'Hello World!',
        description: 'The default message',
    },
    content: {
        id: 'foo.bar.biff',
        defaultMessage: 'Hello Nurse!',
        description: 'Another message',
    },
});

export default class Foo extends Component {
    render() {
        return (
            <div>
                <h1><FormattedMessage {...msgs.header}/></h1>
                <p><FormattedMessage {...msgs.content}/></p>
            </div>
        );
    }
}
```

A proper fix could be checking for `id` presence instead. See: https://github.com/Doctoright/babel-plugin-react-intl/commit/2e13607b63b3ae4aa911a246992ef2c8a4f299af

2019-02-28 15:23 UTC, Keroxo commented
What's the status about this? This PR would be relevant for me too.

2019-03-01 01:54 UTC, rasendubi commented
@Keroxo there seems to be no movement and there is little hope it will be.

I have applied the patch with my fix mentioned above and published it as [@doctoright/babel-plugin-react-intl](https://www.npmjs.com/package/@doctoright/babel-plugin-react-intl).

2019-03-01 07:22 UTC, Keroxo commented
@rasendubi okay. sad to hear that. Thanks for your fast response

2019-05-22 02:17 UTC, longlho commented
Can you add a test please?

2019-05-22 02:29 UTC, longlho requested changes
Can u add tests please?

2019-05-26 01:29 UTC, longlho commented
close due to stale

2019-05-26 01:29 UTC, closed without merging