New options: removeDefaultMessage and keepDescriptions
yahoo/babel-plugin-react-intl pull request #137
Opened 2018-04-08 17:00 UTC by langpavel

New options:
 - `removeDefaultMessage` bool, default false
 - `keepDescriptions` bool, default false

2018-04-08 17:16 UTC, langpavel commented
@ericf First commit will pass tests too if you restart travis

2018-04-24 17:25 UTC, redonkulus commented
@langpavel Will this resolve your issue? https://github.com/yahoo/babel-plugin-react-intl/pull/136/

2018-04-24 17:51 UTC, langpavel commented
Hi @redonkulus 

Actually, I created a [fork](https://github.com/langpavel/babel-plugin-react-intl) and published it at [npm here](https://yarnpkg.com/en/package/@langpavel/babel-plugin-react-intl) with much much more features :tada:
 - It may be configured to keep **only** `id` after processing
 - You can allow another properties, you can then define more like *defaultMessage* for more languages you know when coding,
   like `'en'` for English default message, `'cs'` for Czech default message, etc…
 - I have single file per language dictionaries in customized script, this may be ported into this plugin too…
 - I'm still working on tighter integration with Webpack, so message dictionaries can be loaded automatically and code splitted by chunks (chunkGroups)
 - by default it's compatible with `babel-plugin-react-intl` except configuration:

```typescript
export type BabelPluginReactIntlConfig = {|
  // same as upstream
  moduleSourceName?: string,
  
  // same as upstream
  extractSourceLocation: boolean,
  
  // same as upstream
  enforceDescriptions: boolean,
  
  // names of properties which must be ICU compliant
  messageProps?: string[],
  
  // names of other known properties, which will be extracted
  extraProps?: string[],

  // true → remove all known props except `id`
  // false → do not touch
  // Array — remove only enumerated props
  removeProps?: string[] | boolean,

  // same as upstream
  messagesDir?: string,
|};
```

Here are my defaults:
```javascript
const defaultOptions = {
  // name of import or require module which sense this plugin
  moduleSourceName: 'react-intl',
  // if true, this module will capture exact source location of every definition
  extractSourceLocation: false,
  // require 'description' property in original source
  enforceDescriptions: false,
  // names of properties which must be ICU compliant
  messageProps: ['defaultMessage'],
  // names of other properties which will be extracted
  extraProps: [],
  // names of properties which will be removed from output
  // should contain all messageProps in production build
  removeProps: ['description'],
  // directory, where extracted messages can be written.
  messagesDir: undefined,
};
```

2019-05-22 02:19 UTC, longlho commented
Hi there, do you still want to pursue this PR?

2019-05-22 02:28 UTC, longlho requested changes
Do you still want to pursue this PR?

2019-05-23 17:27 UTC, longlho commented
close due to stale

2019-05-23 17:27 UTC, closed without merging