Export messages by category and other options
yahoo/babel-plugin-react-intl pull request #140
Opened 2018-04-15 18:45 UTC by SleepWalker

This is a first attempt to implement the things, I've described in #128.

This PR includes:

* an option to allow messages with only `id` (without `defaultMessage`)
* an options to override default component names (#138)
* an option to allow parsing messages from imperative api (#18)
* an option to merge all messages into several files by 'category' specified in message id.

2018-04-17 22:06 UTC, langpavel commented
Hi, can you explain why you need *extractInjectionApi* option? ca02535c1026041636767f8e10ad8fccf962e02d
I'm just curious…

2018-04-17 22:57 UTC, langpavel commented
Created https://github.com/epoberezkin/fast-deep-equal/pull/18

2018-04-18 04:43 UTC, SleepWalker commented
> Hi, can you explain why you need extractInjectionApi option?

Hello, this option allows you collect messages directly from the imperative API calls, e.g. from:

```js
intl.formatMessage({
  id: 'foo'
});
```

This option is for the people, who can not understand why do you need to use `defineMessages`. Probably I've missed something, but I can't understand what risks do we have, when we parse intl API directly?

I want the translation to be a little bit easier (for developer), than implementation of an actual product :)

2019-03-08 16:40 UTC, sanbornhilland commented
Hey, I'm wondering if I can help get this moving again. Any particular reason why this stalled?

2019-03-11 14:37 UTC, sanbornhilland commented
As per dan-lee's [comment](https://github.com/yahoo/babel-plugin-react-intl/issues/138#issuecomment-471479903) can we split this out into several PRs? The `COMPONENT_NAME` stuff looks like it would be useful for a number of people and I think it might be easier to get the work reviewed and merged if we had several focused PRs.

2019-03-11 17:48 UTC, SleepWalker commented
There is no reason to do anything, till we get some feedback from the maintainers

2019-05-22 02:18 UTC, longlho commented
Hi there, this PR does a lot of things so would you mind splitting & rebase?

2019-05-22 02:27 UTC, longlho requested changes
This PR does a lot of things can u split & rebase?

2019-05-23 17:24 UTC, longlho commented
Some of the features that this PR includes are already in `master` so closing due to stale.

2019-05-23 17:24 UTC, closed without merging